version: '3.8'

services:

    # MySQL database
    mysql:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: 4fn4@96K
            MYSQL_DATABASE: myreads
        # Remove port exposure when not in development
        ports:
            - "3306:3306"
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - app-network

    # Spring Boot backend
    backend:
        image: myreads-server
        build:
            context: ./server
            dockerfile: Dockerfile
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/myreads
            SPRING_DATASOURCE_USERNAME: root
            SPRING_DATASOURCE_PASSWORD: 4fn4@96K
        # Remove port exposure when not in development
        ports:
            - "8080:8080"
        depends_on:
            mysql:
                condition: service_healthy
        networks:
            - app-network

    # React frontend
    frontend:
        image: myreads-client
        build:
            context: ./client
            dockerfile: Dockerfile
        ports:
            - "3000:80"
        depends_on:
            - backend
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
